### ISSUE TITLE
Merge with JS-CSP

### ISSUE THREAD

**Issue by nmn** [AppliedMathematicsANU/plexus-csp#2]
JS-CSP is another project which is working on something similar. It already has some traction in the community and there is active work going on it.

It would be great if you could join forces. I don't see any particular difference in opinions about the implementation in the two projects.

**Comment by odf** [comment]
While many of the goals are similar, it seems to me that there are in fact significant differences between the two projects. While js-csp aims at being a close port of Clojure's core.async, I've attempted to make some changes in plexus-csp to make it fit in better with the rest of the JavaScript ecosystem. The most significant one is that go routines and channels are completely independent of one another. This makes it relatively easy to interface with promise- and callback-based libraries and also to make exceptions bubble up like in normal synchronous code. I'm not sure how js-csp solves these problems, as I haven't checked their progress lately.

At any rate, it seems that js-csp is vastly more popular and does not need my help.
